import kotlin.String

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Update this file with
 *   `$ ./gradlew buildSrcVersions`
 */
object Libs {
    const val lib1: String = "com.github.danbrough.jitpackdemo:lib1:1.0.2"

    const val lib2: String = "com.github.danbrough.jitpackdemo:lib2:1.0.2"

    const val kotlin_android_extensions: String =
            "org.jetbrains.kotlin:kotlin-android-extensions:1.3.50"

    const val kotlin_android_extensions_runtime: String =
            "org.jetbrains.kotlin:kotlin-android-extensions-runtime:1.3.50"

    const val kotlin_annotation_processing_gradle: String =
            "org.jetbrains.kotlin:kotlin-annotation-processing-gradle:1.3.50"

    const val kotlin_gradle_plugin: String = "org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.50"

    const val kotlin_stdlib_jdk8: String = "org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.3.50"

    const val multidex: String = "androidx.multidex:multidex:2.0.0"

    const val multidex_instrumentation: String = "androidx.multidex:multidex-instrumentation:2.0.0"

    const val com_android_tools_build_gradle: String = "com.android.tools.build:gradle:3.6.0-beta03"

    const val digital_wup_android_maven_publish_gradle_plugin: String =
            "digital.wup.android-maven-publish:digital.wup.android-maven-publish.gradle.plugin:3.6.3"

    const val de_fayard_buildsrcversions_gradle_plugin: String =
            "de.fayard.buildSrcVersions:de.fayard.buildSrcVersions.gradle.plugin:0.7.0"

    const val navigation_safe_args_gradle_plugin: String =
            "androidx.navigation:navigation-safe-args-gradle-plugin:2.1.0"

    const val org_jetbrains_dokka_gradle_plugin: String =
            "org.jetbrains.dokka:org.jetbrains.dokka.gradle.plugin:0.10.0"

    const val constraintlayout: String = "androidx.constraintlayout:constraintlayout:1.1.3"

    const val lint_gradle: String = "com.android.tools.lint:lint-gradle:26.6.0-beta03"

    const val slf4j_api: String = "org.slf4j:slf4j-api:1.7.29"

    const val material: String = "com.google.android.material:material:1.0.0"

    const val aapt2: String = "com.android.tools.build:aapt2:3.6.0-beta03-5836729"
}
